spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finpilot-erp-finance-app
    username: postgres
    password: 6367
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  application:
    name: erp-finance-app